name: Test

on:
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.6

    - name: Setup Go environment
      uses: actions/setup-go@v5.0.1
      with:
        go-version: '1.22.2'

    - name: Test
      run: go test -v ./...
