name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.6

      - name: Setup Go environment
        uses: actions/setup-go@v5.0.1
        with:
          go-version: '1.22.2'

      - name: Install go-semrel
        run: go install github.com/go-semantic-release/semantic-release/cmd/semantic-release@latest

      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: semantic-release